'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { motion,useReducedMotion } from 'framer-motion';
import { Camera as Instagram,UsersRound as Facebook,BriefcaseBusiness as Linkedin,SquarePlay as Youtube,ArrowDownToLine,ArrowUpRight,ArrowLeft,Info,Check,ArrowRight,Globe,CalendarDays,ChevronDown } from 'lucide-react';
import { ResponsiveContainer,RadarChart,PolarGrid,PolarAngleAxis,PolarRadiusAxis,Radar,Tooltip,BarChart,CartesianGrid,XAxis,YAxis,Bar,PieChart,Pie,Cell } from 'recharts';
import type { Report } from '@/lib/report';
import { platformNames,type Platform } from '@/lib/collectors/types';
import { band } from '@/lib/scoring';
import './report.css';
const colors:Record<Platform,string>={instagram:'#c3ed83',facebook:'#8baee5',linkedin:'#b3a0e3',youtube:'#e4ad8b'};
const icons={instagram:Instagram,facebook:Facebook,linkedin:Linkedin,youtube:Youtube};
const display=(n:number|null,digits=0)=>n===null?'Not measured':new Intl.NumberFormat('en-IN',{maximumFractionDigits:digits}).format(n);
const date=(s:string|null)=>s===null?'Not measured':new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'}).format(new Date(s));
const componentNames:Record<string,string>={activity:'Activity',engagement:'Engagement',audience:'Audience',completeness:'Profile'};
export function PlatformIcon({platform,size=17}:{platform:Platform;size?:number}){const Icon=icons[platform];return <span className={`platform-icon ${platform}`}><Icon size={size}/></span>;}
function Ring({score,size=132,color='var(--brand-primary)',print=false}:{score:number|null;size?:number;color?:string;print?:boolean}){
  const reduced=useReducedMotion();const radius=44,circ=2*Math.PI*radius;
  return <div className="score-ring" style={{width:size,height:size}} aria-label={`Score: ${score===null?'Not measured':Math.round(score)+' out of 100'}`}><svg viewBox="0 0 100 100"><circle className="ring-track" cx="50" cy="50" r={radius}/><motion.circle cx="50" cy="50" r={radius} fill="none" stroke={color} strokeWidth="5" strokeLinecap="round" strokeDasharray={circ} initial={print||reduced?false:{strokeDashoffset:circ}} animate={{strokeDashoffset:circ*(1-(score??0)/100)}} transition={{duration:1.1,ease:'easeOut'}} transform="rotate(-90 50 50)"/></svg><div className="ring-label"><strong>{score===null?'—':Math.round(score)}</strong>{size>90&&<span>OUT OF 100</span>}</div></div>;
}
export interface ReportProps {id:string;brand:string;website:string|null;report:Report;print?:boolean}
export function SocialReport({id,brand,website,report,print=false}:ReportProps){
  const [ready,setReady]=useState(false);const [pdfBusy,setPdfBusy]=useState(false);const [error,setError]=useState('');const reduced=useReducedMotion();
  useEffect(()=>{const id=setTimeout(()=>setReady(true),350);return()=>clearTimeout(id);},[]);
  const measured=report.cards.filter(c=>c.score!==null);const best=[...measured].sort((a,b)=>(b.score??0)-(a.score??0))[0];
  const verdict=report.social===null?'There is not enough measured data to assess this brand yet.':report.social>=80?'A strong foundation. Keep turning attention into connection.':report.social>=60?'A promising presence, with room to make a bigger impression.':'The next chapter starts with showing up consistently.';
  const radarData=Object.keys(componentNames).map(key=>({component:componentNames[key],...Object.fromEntries(report.cards.map(c=>[c.platform,c.components[key as keyof typeof c.components]]))}));
  const download=async()=>{setPdfBusy(true);setError('');try{const res=await fetch(`/api/audits/${id}/pdf`);if(!res.ok){const data=await res.json();throw new Error(data.error??'PDF export failed.');}const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${brand.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-social-audit.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Unable to export PDF.');}finally{setPdfBusy(false);}};
  return <article className={`social-report ${print?'print-report':''}`} data-report-ready={ready?'true':'false'}>
    <div className="report-page report-page-one">
    {!print&&<Link className="back-link" href="/history"><ArrowLeft size={13}/>Back to audit library</Link>}
    <div className="page-heading"><div><span className="eyebrow">SOCIAL PRESENCE REPORT</span><h1>{brand}<span className="brand-dot">.</span></h1><div className="report-meta"><span><Globe size={12}/>{website?new URL(website).hostname:'No website provided'}</span><span><CalendarDays size={12}/>{date(report.asOf)}</span><span>#{id.slice(-8).toUpperCase()}</span></div></div>{!print&&<div className="actions"><Link className="button" href={`/audits/new?from=${id}`}>Re-run audit<ArrowUpRight size={15}/></Link><button className="button primary" onClick={download} disabled={pdfBusy}><ArrowDownToLine size={16}/>{pdfBusy?'Preparing PDF…':'Download PDF'}</button></div>}</div>
    {error&&<p className="error" role="alert">{error}</p>}
    <div className="report-disclaimer"><span><Info size={13}/>Illustrative report · synthetic data</span><span>4 platforms · placeholder benchmarks · {report.industry}</span></div>
    <section className="hero-panel"><div className="hero-score"><Ring score={report.overall.score} size={170} print={print}/><div className="score-caption">{report.overall.label}</div></div><div className="hero-copy"><div className={`score-band band-${band(report.social,report.config).toLowerCase().replace(' ','-')}`}><span/> {band(report.social,report.config)} presence</div><h2>{verdict}</h2><p>{best?`${platformNames[best.platform]} leads the way. ${report.gaps.length?`${report.gaps.length} opportunities below point to where your next effort could count most.`:'Keep the momentum with a consistent, thoughtful content strategy.'}`:'Confirm accounts and collect public data to reveal opportunities.'}</p><div className="hero-facts"><div><strong>{measured.length}<small> / 4</small></strong><span>Platforms scored</span></div><div><strong>{report.gaps.length}</strong><span>Priority opportunities</span></div><div><strong>{report.costUsd===null?'Unknown':`$${report.costUsd.toFixed(2)}`}</strong><span>Collection cost</span></div></div></div><span className="hero-decoration" aria-hidden="true">↗</span></section>
    <details className="score-explainer"><summary><Info size={13}/>How this score is calculated<ChevronDown size={13}/></summary><p>Only Social is measured in this version, so its overall weight is 100%. Website (configured {report.config.channels.website}%) and Google Business Profile ({report.config.channels.gbp}%) are excluded. Unavailable components and platforms are excluded; confirmed absent relevant accounts score 0. Platform scores use unrounded values.</p><div className="explain-grid">{report.cards.map(c=><div key={c.platform}><strong>{platformNames[c.platform]}: {display(c.score,1)}</strong><span>Effective weight {display(report.platformWeights[c.platform],1)}% · configured {report.config.industries[report.industry].weights[c.platform]}%</span></div>)}</div></details>
    <div className="section-heading platform-section-title"><h2>The platform picture</h2><span className="muted">A snapshot of where the brand stands</span></div>
    <section className="platform-grid">{report.cards.map((card,i)=><motion.div key={card.platform} className="panel platform-card" initial={print||reduced?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.06}}><div className="platform-card-title"><PlatformIcon platform={card.platform}/><strong>{platformNames[card.platform]}</strong><span className={`status-pill status-${card.status}`}>{card.status==='ok'?'Measured':card.status==='absent'?'No account':card.status.replace('_',' ')}</span></div><div className="platform-score"><Ring score={card.score} size={74} color={colors[card.platform]} print={print}/><div><strong>{band(card.score,report.config)}</strong><span>{card.handle?`@${card.handle}`:'No confirmed handle'}</span></div></div><dl><div><dt>{card.platform==='youtube'?'Subscribers':'Followers'}</dt><dd>{card.subscriberHidden?'Hidden':display(card.profile?.followers??null)}</dd></div><div><dt>Posts / 30 days</dt><dd>{card.metrics.lowerBound?'≥ ':''}{display(card.metrics.count)}</dd></div><div><dt>Engagement rate</dt><dd>{card.metrics.engagement===null?'Not measured':`${display(card.metrics.engagement,2)}%`}</dd></div><div><dt>Last post</dt><dd>{date(card.metrics.lastPost)}</dd></div></dl><details className="platform-details"><summary>Score breakdown <ChevronDown size={12}/></summary>{Object.entries(card.components).map(([key,value])=><div className="component-row" key={key}><span>{componentNames[key]}</span><strong>{display(value,1)}</strong><small>{display(card.weights[key],1)}% weight</small></div>)}<p>Targets: {card.benchmark.postsTarget} posts/month · {card.benchmark.engagementTarget}% engagement · {display(card.benchmark.followerLow)}–{display(card.benchmark.followerHigh)} followers.</p><p>Observed longest gap: {display(card.metrics.longestGap,1)} days. Avg likes: {display(card.metrics.avgLikes,1)}; avg comments: {display(card.metrics.avgComments,1)}. Profile checks: {display(card.metrics.completeness,1)}%.</p></details></motion.div>)}</section>
    </div>
    <div className="report-page report-page-two">
    <section className="grid-2 chart-grid"><div className="panel"><SectionTitle title="Beyond the follower count" subtitle="Four dimensions of a healthy social presence" number="01"/><div className="chart-frame radar-frame" role="img" aria-label="Radar chart comparing activity, engagement, audience and profile scores"><ResponsiveContainer width="100%" height="100%"><RadarChart data={radarData} outerRadius="72%"><PolarGrid stroke="var(--line)"/><PolarAngleAxis dataKey="component" tick={{fill:'var(--muted)',fontSize:11}}/><PolarRadiusAxis domain={[0,100]} tick={false} axisLine={false}/>{report.cards.filter(c=>Object.values(c.components).every(v=>v!==null)).map(c=><Radar key={c.platform} dataKey={c.platform} stroke={colors[c.platform]} fill={colors[c.platform]} fillOpacity={.08} strokeWidth={2} isAnimationActive={false}/>)}<Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--line)',borderRadius:8}}/></RadarChart></ResponsiveContainer></div><div className="chart-legend">{report.cards.map(c=><span key={c.platform}><i style={{background:colors[c.platform]}}/>{platformNames[c.platform]}</span>)}</div><p className="chart-note">Incomplete component sets are omitted from the radar; values remain available in each score breakdown.</p></div>
    <div className="panel"><SectionTitle title="Attention meets interaction" subtitle="Engagement rate alongside audience size" number="02"/><div className="chart-frame" role="img" aria-label="Bar chart of engagement rates by platform"><ResponsiveContainer width="100%" height="100%"><BarChart data={report.cards.map(c=>({name:platformNames[c.platform],engagement:c.metrics.engagement,platform:c.platform}))} margin={{left:-20,right:8,top:22,bottom:0}}><CartesianGrid stroke="var(--line)" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="name" tick={{fill:'var(--muted)',fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fill:'var(--muted)',fontSize:10}} tickFormatter={v=>`${v}%`} axisLine={false} tickLine={false}/><Tooltip cursor={{fill:'var(--line)'}} contentStyle={{background:'var(--panel)',border:'1px solid var(--line)'}} formatter={v=>[`${Number(v).toFixed(2)}%`,'Engagement']}/><Bar dataKey="engagement" radius={[5,5,0,0]} maxBarSize={38} isAnimationActive={false}>{report.cards.map(c=><Cell key={c.platform} fill={colors[c.platform]}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="audience-strip">{report.cards.map(c=><div key={c.platform}><strong>{c.subscriberHidden?'Hidden':display(c.profile?.followers??null)}</strong><span>{platformNames[c.platform]} audience</span><small>{c.metrics.engagement===null?'Rate not measured':`${display(c.metrics.engagement,2)}% engagement`}</small></div>)}</div></div></section>
    <section className="panel calendar-panel"><SectionTitle title="Consistency leaves a pattern" subtitle="Observed posting activity · last 90 days · Asia/Kolkata · pinned posts excluded" number="03"/><div className="calendar-scroll"><div className="calendar-months"><span/>{[0,30,60,89].map(i=><span key={i}>{date(new Date(new Date(report.asOf).getTime()-(89-i)*86400000).toISOString()).split(' ').slice(0,2).join(' ')}</span>)}</div>{report.cards.map(card=><div className="calendar-row" key={card.platform}><span><PlatformIcon platform={card.platform} size={13}/>{platformNames[card.platform]}</span>{card.metrics.calendar?<div className="calendar-cells">{card.metrics.calendar.map(day=><div key={day.date} className={`calendar-cell level-${Math.min(day.count,3)}`} title={`${day.date}: ${day.count} observed posts`} aria-label={`${day.date}: ${day.count} observed posts`}/>)}</div>:<div className="calendar-missing">Not measured — {card.status}</div>}</div>)}</div><div className="calendar-key"><span>Empty cells mean no posts observed, not confirmed inactivity.</span><span>Less <i className="level-0"/><i className="level-1"/><i className="level-2"/><i className="level-3"/> More</span></div></section>
    </div>
    <div className="report-page report-page-three">
    <section className="panel content-panel"><SectionTitle title="A balanced content diet" subtitle="Video and reels versus static formats in the fetched sample" number="04"/><div className="mix-grid">{report.cards.map(c=><div className="mix-item" key={c.platform}><div className="mix-chart" role="img" aria-label={`${platformNames[c.platform]}: ${c.metrics.mix?Math.round(c.metrics.mix.videoPercent)+'% video':'Not measured'}`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={c.metrics.mix?[{name:'Video / reels',value:c.metrics.mix.video},{name:'Static',value:c.metrics.mix.static}]:[{name:'Not measured',value:1}]} dataKey="value" innerRadius={38} outerRadius={48} paddingAngle={c.metrics.mix?3:0} stroke="none" isAnimationActive={false}><Cell fill={c.metrics.mix?colors[c.platform]:'var(--line)'}/><Cell fill="var(--line)"/></Pie></PieChart></ResponsiveContainer><span>{c.metrics.mix?`${Math.round(c.metrics.mix.videoPercent)}%`:'—'}<small>{c.metrics.mix?'video':'not measured'}</small></span></div><strong>{platformNames[c.platform]}</strong><p>{c.metrics.mix?`${c.metrics.mix.video} video · ${c.metrics.mix.static} static`:'Not measured'}</p></div>)}</div></section>
    <section className="panel top-posts-panel"><SectionTitle title="Content that connected" subtitle="Top posts per platform by measured likes + comments" number="05"/><div className="top-post-grid">{report.cards.map(c=><div key={c.platform}><h3><PlatformIcon platform={c.platform} size={14}/>{platformNames[c.platform]}</h3>{c.metrics.top.length?c.metrics.top.map((p,i)=><div className="post-item" key={p.id}><span className="post-rank">0{i+1}</span><div><span className="post-format">{p.type} · {date(p.publishedAt)}</span><p>{p.captionPreview??'Caption not measured'}</p><small>{display(p.likes)} likes <span>·</span> {display(p.comments)} comments</small>{p.url?<a href={p.url} target="_blank" rel="noreferrer">View post <ArrowUpRight size={11}/></a>:<span className="mock-post-note">Illustrative post · no live link</span>}</div></div>):<p className="muted">No posts with measured likes and comments.</p>}</div>)}</div></section>
    </div>
    <div className="report-page report-page-four">
    <section className="opportunities"><div className="section-heading"><div><span className="eyebrow">FROM INSIGHT TO ACTION</span><h2>Small shifts. Meaningful impact.</h2><p>Your highest-priority opportunities, paired with a way forward.</p></div><span className="tag">{report.gaps.length} quick wins</span></div><div className="gap-grid">{report.gaps.length?report.gaps.map((gap,i)=><div className="panel gap-card" key={`${gap.platform}-${gap.component}`}><div className="gap-header"><span className="gap-index">0{i+1}</span><span className="tag">{platformNames[gap.platform as Platform]} · {gap.score.toFixed(0)}/100</span></div><h3>{gap.component==='missing'?`Build a presence on ${platformNames[gap.platform as Platform]}`:gap.component==='video'?'Bring the story to life with video':gap.component==='activity'?'Close the gaps in your calendar':gap.component==='engagement'?'Give your audience a reason to respond':gap.component==='audience'?'Reach more of the right people':'Make the first impression complete'}</h3><div className="gap-measure">{gap.measured}</div><p>{gap.explanation}</p><div className="service-link">{gap.service}<ArrowRight size={14}/></div></div>):<div className="panel"><Check size={20}/><h3>{report.social===null?'No measured opportunities yet':'A strong starting point'}</h3><p>{report.social===null?'Collect usable data before drawing conclusions.':'No measured component falls below the configured threshold.'}</p></div>}</div></section>
    <section className="panel data-notes"><SectionTitle title="The context behind the numbers" subtitle="Data notes, limitations and provenance" number="06"/><div className="data-note-intro"><Info size={16}/><p>This is a mock report, built from stored synthetic fixtures. Benchmarks are placeholders, not industry research. Website and Google Business Profile have not been measured. No live accuracy or coverage claim is made.</p></div><div className="notes-grid">{report.cards.map(c=><div key={c.platform}><strong>{platformNames[c.platform]}</strong><ul>{c.metrics.notes.filter((n,i)=>i!==0||!n.startsWith('Synthetic')).map((note,i)=><li key={i}>{note}</li>)}{Object.entries(c.components).filter(([,v])=>v===null).map(([k])=><li key={k}>{componentNames[k]} not measured; excluded from score.</li>)}</ul><small>Data timestamp: {new Date(c.fetchedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</small></div>)}</div>{!print&&<a className="raw-link" href={`/api/audits/${id}/raw`} target="_blank" rel="noreferrer">Inspect stored source responses <ArrowUpRight size={13}/></a>}</section>
    <div className="report-closing"><span className="wordmark">tier2<span>®</span></span><div>Built for the next chapter.<span>Strategy · Creativity · Growth</span></div><span>tier2.digital</span></div>
    </div>
  </article>;
}
function SectionTitle({title,subtitle,number}:{title:string;subtitle:string;number:string}) {return <div className="section-heading"><div><h2>{title}</h2><p>{subtitle}</p></div><span className="section-number">{number}</span></div>;}

